# Generated by Django 5.2.5 on 2026-03-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoultryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(help_text='e.g. Broilers March 2026', max_length=100)),
                ('number_of_chickens', models.PositiveIntegerField()),
                ('chick_purchase_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('feed_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, help_text='Medicines, charcoal, etc.', max_digits=12)),
                ('total_sales_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_started', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Poultry Record',
                'verbose_name_plural': 'Poultry Records',
                'ordering': ['-date_started'],
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('total_fees_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Fee',
                'verbose_name_plural': 'Student Fees',
                'ordering': ['student_name'],
            },
        ),
    ]
