# Generated by Django 5.2.5 on 2026-03-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalChickenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(help_text='e.g. Village Mix April', max_length=100)),
                ('number_of_birds', models.PositiveIntegerField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('feed_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_sales_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_started', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Local Chicken Record',
                'verbose_name_plural': 'Local Chicken Records',
                'ordering': ['-date_started'],
            },
        ),
        migrations.CreateModel(
            name='PiggeryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(help_text='e.g. Large White Batch A', max_length=100)),
                ('number_of_pigs', models.PositiveIntegerField()),
                ('piglet_purchase_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('feed_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('treatment_cost', models.DecimalField(decimal_places=2, default=0, help_text='Vaccinations and deworming', max_digits=12)),
                ('total_sales_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_started', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Piggery Record',
                'verbose_name_plural': 'Piggery Records',
                'ordering': ['-date_started'],
            },
        ),
        migrations.CreateModel(
            name='SchoolExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='e.g. Electricity, Water, Stationery', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_spent', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_spent'],
            },
        ),
        migrations.AlterField(
            model_name='poultryrecord',
            name='chick_purchase_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cost of Birds'),
        ),
        migrations.AlterField(
            model_name='poultryrecord',
            name='feed_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cost of Food'),
        ),
    ]
