# Generated by Django 5.2.5 on 2026-05-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_localchickenrecord_piggeryrecord_schoolexpense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolexpense',
            name='academic_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='schoolexpense',
            name='term',
            field=models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], default='Term 1', max_length=10),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='academic_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='term',
            field=models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], default='Term 1', max_length=10),
        ),
    ]
