# Generated by Django 5.2.5 on 2025-08-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0002_remove_question_correct_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('SA', 'Single Answer')], default='MC', max_length=2),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
