# Generated by Django 5.2.5 on 2025-08-31 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0003_question_correct_answer_text_question_question_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['text']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Student Answers'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(help_text='The question this choice belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='aiapp.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer_text',
            field=models.TextField(blank=True, help_text='The correct answer text for single-answer questions.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(help_text='The quiz this question belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='aiapp.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='teacher',
            field=models.ForeignKey(help_text='The user who created this quiz.', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, help_text='The selected choice for a multiple-choice question.', null=True, on_delete=django.db.models.deletion.CASCADE, to='aiapp.choice'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='text_answer',
            field=models.TextField(blank=True, help_text='The text entered by the student for a single-answer question.', null=True),
        ),
    ]
