# Generated by Django 5.2.5 on 2025-09-03 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0005_attempt_studentanswer_attempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'quiz'], name='aiapp_attem_user_id_0b6b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['attempt', 'question'], name='aiapp_stude_attempt_4a6a76_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['student', 'question'], name='aiapp_stude_student_97620c_idx'),
        ),
    ]
