# Generated by Django 5.2.5 on 2025-09-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0006_alter_attempt_submission_date_alter_quiz_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='upload_code',
            field=models.CharField(blank=True, help_text='Admin-provided code to authorize uploads.', max_length=10, null=True),
        ),
    ]
