# Generated by Django 5.2.5 on 2025-11-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Phone Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Ad Click Points'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Reward Amount (UGX)'),
        ),
    ]
