# Generated by Django 5.2.5 on 2025-11-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_mobile_number_profile_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_clicks',
            field=models.IntegerField(default=0, verbose_name='Total Clicks'),
        ),
    ]
