# Generated by Django 5.2.5 on 2025-11-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_total_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', verbose_name='Profile Avatar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, default='covers/default_cover.jpg', null=True, upload_to='covers/', verbose_name='Cover Image'),
        ),
    ]
