# Generated by Django 5.2.5 on 2025-11-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_avatar_profile_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ad Click Points'),
        ),
    ]
